In [ ]:
conda install numpy

In [3]:
pip insatall numy

Note: you may need to restart the kernel to use updated packages.


ERROR: unknown command "insatall" - maybe you meant "install"



In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [9]:
my_list = [10,20,30,40]

In [11]:
type my_list

SyntaxError: invalid syntax (2784429415.py, line 1)

In [13]:
my_list.type

AttributeError: 'list' object has no attribute 'type'

In [15]:
type(my_list)

list

In [17]:
np.array(my_list)

array([10, 20, 30, 40])

In [19]:
my_numpy_array = np.array(my_list)

In [21]:
type(my_numpy_array)

numpy.ndarray

In [23]:
my_numpy_array

array([10, 20, 30, 40])

In [56]:
my_numpy_array[1]

NameError: name 'my_numpy_array' is not defined

my_numpy_arrsy[-1]

40

In [30]:
my_numpy_array[0] = 100

In [32]:
my_numpy_array

array([100,  20,  30,  40])

In [36]:
my_numpy_array.max()

100

In [38]:
my_numpy_array.min()

20

In [40]:
my_numpy_array.mean()

47.5

In [44]:
matrix_list = [ [1,0,0], [0,1,0], [0,0,1],[0,0,0] ]
               

In [46]:
type(matrix_list)

list

In [48]:
matrix_list[0][0]

1

önemli

önemli

In [56]:
numpy_matrix_list = np.array(matrix_list)

[[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 0]]

In [58]:
numpy_matrix_list

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [60]:
numpy_matrix_list.shape

(4, 3)

In [62]:
list(range (0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [1]:
np.arange(0,10)

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
print("hi")

hi


In [9]:
print("hi")

hi


In [3]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [5]:
import numpy as np

In [17]:
np.arange(9999999)

array([      0,       1,       2, ..., 9999996, 9999997, 9999998])

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [30]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [42]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [48]:
np.random.randint(1,10,3) 

array([2, 4, 5])

In [6]:
import numpy as np

In [8]:
my_numpy_list=np.arange(0,20)

In [10]:
my_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
my_numpy_list[4]


4

In [16]:
my_numpy_list[4:9]

array([4, 5, 6, 7, 8])

In [18]:
my_numpy_list[4:9:2]

array([4, 6, 8])

In [20]:
my_list = list(range(0,20))

In [24]:
#my_list[4:9] = -10
#error

In [26]:
my_numpy_list[4:9] = -10 

In [28]:
my_numpy_list

array([  0,   1,   2,   3, -10, -10, -10, -10, -10,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [34]:
other_list = np.arange(0,15)

In [36]:
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
silicsing_list = other_list[4:10]

In [40]:
silicsing_list[:] = 100

In [42]:
other_list

array([  0,   1,   2,   3, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14])

In [54]:
new_array=np.random.randint(1,150,25)

In [56]:
new_array

array([ 83, 106,  59, 142,  56, 130, 145,  83, 107,  79, 102,  23, 137,
        82, 104,  35,  13, 105, 119,  10,   8,  13,  94,  75, 112])

In [58]:
new_array > 50

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False,  True,
        True, False, False, False,  True,  True,  True])

In [62]:
result_array = new_array > 50

In [65]:
new_array[result_array]

array([ 83, 106,  59, 142,  56, 130, 145,  83, 107,  79, 102, 137,  82,
       104, 105, 119,  94,  75, 112])

In [67]:
last_array = np.arange(0,30)

In [69]:
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [71]:
last_array + last_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [73]:
last_array * last_array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [75]:
last_array - last_array 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [77]:
last_array / last_array

C:\Users\Master\AppData\Local\Temp\ipykernel_16576\3398326563.py:1: RuntimeWarning: invalid value encountered in divide
  last_array / last_array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [79]:
np.max(last_array)

29

In [81]:
np.mean(last_array)

14.5

In [83]:
np.sqrt(last_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])